### ISSUE TITLE
Cannot read property 'text' of undefined(ng serve --prod --aot)

### ISSUE THREAD

**Issue by zhongzhong0505** [amcharts/amcharts3-angular2#22]
`Failed to compile.

./~/.1.1.0@amcharts3-angular2/index.ts
Module build failed: TypeError: Cannot read property 'text' of undefined
    at Object.getTokenPosOfNode (E:\work\CodeBe\node_modules\.2.2.1@typescript\lib\typescript.js:6768:71)
    at IdentifierObject.TokenOrIdentifierObject.getStart (E:\work\CodeBe\node_modules\.2.2.1@typescript\lib\typescript.js:80500:23)
    at IdentifierObject.TokenOrIdentifierObject.getText (E:\work\CodeBe\node_modules\.2.2.1@typescript\lib\typescript.js:80521:77)
    at refactor.findAstNodes.filter (E:\work\CodeBe\node_modules\.1.2.12@@ngtools\webpack\src\loader.js:139:44)
    at Array.filter (native)
    at refactor.findAstNodes.forEach.node (E:\work\CodeBe\node_modules\.1.2.12@@ngtools\webpack\src\loader.js:138:14)
    at Array.forEach (native)
    at _removeDecorators (E:\work\CodeBe\node_modules\.1.2.12@@ngtools\webpack\src\loader.js:129:10)
    at Promise.resolve.then (E:\work\CodeBe\node_modules\.1.2.12@@ngtools\webpack\src\loader.js:292:33)
 @ ./src/$$_gendir/app/home/home.module.ngfactory.ts 25:0-52
 @ ./src/$$_gendir async
 @ ./~/.2.4.9@@angular/core/src/linker/system_js_ng_module_factory_loader.js
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts`

**Comment by BlandLi** [comment]
So, check if the 3rd party component has ts source files published in the module (excluding the d.ts files since those are needed).

The CLI errored out in our case if they are there.

e.g.

/node_modules/@covalent/core/index.ts was the guilty file, so we had to remove the source typescript files from the publishing process (which was our fault to begin with since they shouldnt be published, only the js files should be published)

**Comment by BlandLi** [comment]
i publish a fixed version , maybe you can use this,amcharts3-angular2-fix-error@1.2.0

**Comment by Pauan** [comment]
Please try again with `@amcharts/amcharts3-angular` version `1.2.1`
