### ISSUE TITLE
Ionic2 Application fails to Build/Transpile

### ISSUE THREAD

**Issue by delian7** [amcharts/amcharts3-angular2#6]
Here's my output: 

```
[14:06:29]  Error: Error at /Users/DelianPetrov/Sites/seastatus/.tmp/app/amcharts.directive.ngfactory.ts:45:34 
[14:06:29]  Argument of type '{ [key: string]: any; }' is not assignable to parameter of type '{ options 
[14:06:29]  SimpleChange; }'. 
[14:06:29]  Property 'options' is missing in type '{ [key 
[14:06:29]  string]: any; }'. 
[14:06:29]  ngc failed 
[14:06:29]  ionic-app-script task: "build" 
[14:06:29]  Error: Error 
```

It seems that this is the root of the issue: 

```
  detectChangesInternal(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) {
      if (changed) {
        this.context.ngOnChanges(this.changes);
        this.changes = {};
      }
      if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); }
    }
    return changed;
  }
```

**Comment by zaggy** [comment]
I have the same issue.

**Comment by delian7** [comment]
@zaggy Have you tried upgrading to the now stable Ionic 2.0.0. I think as of RC5 + this has not been an issue for me.

**Comment by Pauan** [comment]
@delian7 @zaggy Is this still an issue with `amcharts3-angular2` version `1.1.0` and `ionic` version `2.2.1`?

**Comment by delian7** [comment]
@Pauan I don't see this error anymore.

**Comment by zaggy** [comment]
Hi,

I still have the same issue when I try to use AOT compiling. The same exact error appers:

```
Error: Error at C:/project/compiled/node_modules/amcharts3-angular2/index.ngfactory.ts:71:34: Argument of type '{ [key: string]: any; }' is not assignable to parameter of type '{ options: SimpleChange; }'.
  Property 'options' is missing in type '{ [key: string]: any; }'.
    at new UserError (C:\Apps\_\Projects\CSharp\PIWeb\PiWeb.External\node_modules\tools\@angular\tsc-wrapped\src\tsc.ts:33:25)
    at check (C:\Apps\_\Projects\CSharp\PIWeb\PiWeb.External\node_modules\tools\@angular\tsc-wrapped\src\tsc.ts:69:11)
    at Tsc.typeCheck (C:\Apps\_\Projects\CSharp\PIWeb\PiWeb.External\node_modules\tools\@angular\tsc-wrapped\src\tsc.ts:152:5)
    at C:\Apps\_\Projects\CSharp\PIWeb\PiWeb.External\node_modules\tools\@angular\tsc-wrapped\src\main.ts:68:11
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
